#  Docker-compose for integrating different images, Neo4j, Kafka Broker, Zookeeper, Spark Master and Worker Node
#  Authored: hcwong2@illinois.edu, manaskm2@illinois.edu, fmc2@illinois.edu, skusuma3@illinois.edu

version: "3"

services:

  neo4j:
    image: neo4j:3.5.4
    env_file: neoEnv.env
    #networks:
      #- neo4j-network
    volumes:
    #  - ./db/dbms:/data/dbms
      - ./db/data:/data
      - ./db/config:/conf
      - ./db/plugins:/plugins
      - ./db/logs:/logs
    ports:
    - '7474:7474'
    - '7473:7473'
    - '7687:7687'
    expose:
      - '7474'
      - '7687'

  zookeeper:
    image: wurstmeister/zookeeper:latest
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    expose:
      - '2181'

  broker:
    image: wurstmeister/kafka:2.12-2.1.0
    #hostname: broker
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      #KAFKA_ADVERTISED_LISTENERS:  PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: LISTENER_IN://0.0.0.0:19092, LISTENER_OUT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_IN://broker:19092, LISTENER_OUT://localhost:9092
      #KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      #KAFKA_ADVERTISED_LISTENERS: LISTENER_IN://broker:9092, LISTENER_OUT://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_IN:PLAINTEXT,LISTENER_OUT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_IN
      #KAFKA_DEFAULT_REPLICATION_FACTOR: 1

  sparkMaster:
    image: gettyimages/spark:2.4.0-hadoop-3.0
    command: ./bin/spark-class org.apache.spark.deploy.master.Master -i spark-master
    hostname: 'spark-master'
    container_name: 'spark-master'
    expose:
    - 8080
    - 7077
    volumes:
    - ./spark/spark-master:/opt/spark/dist/logs/
    - ./spark/data:/opt/spark/data/
    - ./spark/code:/opt/spark/code/
    ports:
    - '7077:7077'
    - '8080:8080'
    - '4040:4040'
    - '4041:4041'
    - '4042:4042'
    environment:
      SERVICE_NAME: "spark-master"
      SPARK_USER: "root"
      SPARK_MASTER_PORT: 7077
      SPARK_MASTER_WEBUI_PORT: 8080
    links:
    - neo4j
    - zookeeper
    - broker

  sparkWorker:
      image: gettyimages/spark:2.4.0-hadoop-3.0
      command: ./bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
      hostname: "spark-worker"
      container_name: "spark-worker"
      environment:
        SERVICE_NAME: "spark-worker"
        SPARK_USER: "root"
        SPARK_WORKER_PORT: 8888
        SPARK_WORKER_WEBUI_PORT: 8081
      expose:
      - 8888
      - 8081
      links:
      - sparkMaster
      - neo4j
      - zookeeper
      - broker
      volumes:
      - ./spark/spark-worker:/opt/spark/dist/logs/
      - ./spark/data:/opt/spark/data/
      - ./spark/code:/opt/spark/code/
      ports:
      - '8081:8081'
